# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine :

    # configure resolvers
    resolvers :

        # setup the default resolver
        default :

            # use the default web path
            web_path :
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    # your filter sets are defined here
    filter_sets :

        # use the default cache configuration
        cache :
        thumb : 
            quality: 75
            filters:
                thumbnail: { size:[360,230], mode: outbound}
        medium : 
            quality: 75
            filters:
                thumbnail: { size:[800,530], mode: outbound}